version: '3'
services:
  geoserver:
    image: oscarfonts/geoserver:latest
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - ./data:/opt/geoserver/data_dir
    restart: always
